#!/bin/sh

VENDOR=hisense
DEVICE=msm7627a-common
OUTDIR=vendor/$VENDOR/$DEVICE
MAKEFILE=../../../$OUTDIR/msm7627a-common-vendor-blobs.mk

(cat << EOF) > $MAKEFILE
# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh
PRODUCT_COPY_FILES += \\
EOF
LINEEND=" \\"
COUNT=`cat proprietary-files.txt | grep -v ^# | grep -v ^$ | wc -l | awk {'print $1'}`
for FILE in `cat proprietary-files.txt | grep -v ^# | grep -v ^$`; do
    COUNT=`expr $COUNT - 1`
    if [ $COUNT = "0" ]; then
        LINEEND=""
    fi
    echo "    $OUTDIR/proprietary/$FILE:$FILE$LINEEND" >> $MAKEFILE
done
(cat << EOF) > ../../../$OUTDIR/BoardConfigVendor.mk
# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

# audio
PRODUCT_COPY_FILES += \\
    $OUTDIR/proprietary/system/lib/libaudioalsa.so:obj/lib/libaudioalsa.so

# gps
PRODUCT_COPY_FILES += \\
    $OUTDIR/proprietary/system/lib/libcommondefs.so:obj/lib/libcommondefs.so

# camera
PRODUCT_COPY_FILES += \\
    $OUTDIR/proprietary/system/lib/libmmstillomx.so:obj/lib/libmmstillomx.so \\
    $OUTDIR/proprietary/system/lib/libimage-jpeg-enc-omx-comp.so:obj/lib/libimage-jpeg-enc-omx-comp.so \\
    $OUTDIR/proprietary/system/lib/libmmjpeg.so:obj/lib/libmmjpeg.so

# Vendor extension library
PRODUCT_PROPERTY_OVERRIDES += \\
    ro.vendor.extension_library=/system/lib/libqc-opt.so

PRODUCT_COPY_FILES += \\
    $OUTDIR/proprietary/system/lib/libqc-opt.so:obj/lib/libqc-opt.so
EOF

